---
title: "Data Exploration and Visualization of Child Illiteracy and Learning Poverty"
author: "Connor Piercy"
format: 
 html:
    theme: cosmo
---

## Introduction

This is a report and data exploration into 6 datasets looking at child illiteracy and learning poverty. The Data highlights children aged 0-10 years old across 69 countries. 

Data was obtained from Kaggle by Zkskhurram called Global Child Illiteracy Dataset Children 10 YRS [Kaggle Data](https://www.kaggle.com/datasets/zkskhurram/global-child-illiteracy-dataset-children-10-yrs)

This project will explore each of the following data sets to find indicators and key information to help explain child illiteracy and learning poverty: 

1. Child Illiteracy by Country
2. Child Illiteracy Regional Trends
3. Foundational Skills Assessments
4. Intervention Programs
5. Learning Poverty Indicators
6. Out of School Children

For more information about each of these data sets either continue reading or follow the link above to the original Kaggle Data page for you to also explore. 

```{python}
#| include: false
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from itables import show
import plotly.graph_objects as go
import plotly.express as px

project_dir = Path.cwd()
archive_dir = project_dir / "archive"

if not archive_dir.exists():
    archive_dir = project_dir.parent / "archive"

csv_files = {
    "child_illiteracy_by_country": archive_dir / "child_illiteracy_by_country.csv",
    "child_illiteracy_regional_trends": archive_dir / "child_illiteracy_regional_trends.csv",
    "foundational_skills_assessment": archive_dir / "foundational_skills_assessment.csv",
    "intervention_programs": archive_dir / "intervention_programs.csv",
    "learning_poverty_indicators": archive_dir / "learning_poverty_indicators.csv",
    "out_of_school_children": archive_dir / "out_of_school_children.csv",
}

dataframes = {}

for name, path in csv_files.items():
    if path.exists():
        dataframes[name] = pd.read_csv(path)
        print(f"{name}: {len(dataframes[name])} rows, {len(dataframes[name].columns)} columns")
    else:
        print(f"Missing file: {path}")

child_illiteracy_by_country = dataframes.get("child_illiteracy_by_country")
child_illiteracy_regional_trends = dataframes.get("child_illiteracy_regional_trends")
foundational_skills_assessment = dataframes.get("foundational_skills_assessment")
intervention_programs = dataframes.get("intervention_programs")
learning_poverty_indicators = dataframes.get("learning_poverty_indicators")
out_of_school_children = dataframes.get("out_of_school_children")

```

### 1. Child Illiteracy by Country

Table containing each country in the data set with there data on learning poverty, primary school completion, out of school rate, foundational reading, and foundational numeracy percentages each year, as well as other key student population statistics 

```{python}
#| echo: false
#| output: true
theme_child_illiteracy_by_country = child_illiteracy_by_country.style\
    .set_table_styles([
        {"selector": "th", "props": [("background-color", "#1E3A8A"), ("color", "white")]}
    ])\
    .set_properties(**{
        "background-color": "#F3F4F6",
        "color": "#111827",
        "border-color": "#CBD5E1"
    })
show(theme_child_illiteracy_by_country, allow_html=True, columnDefs=[
            {
                'targets': '_all',
                'className': 'dt-left'
            }
    ], pageLength= 16, lengthMenu=[[16,32,48,64], [16,32,48,64]
    ])
```

Descriptive statistics for the child illiteracy by country data set. This includes the mean, standard deviation, minimum, maximum, and quartiles for each of the numeric columns in the data set.

```{python}
#| label: tbl-interactive
#| tbl-cap: "Summary Statistics"
#| include: false

#Summary
summary_stats = child_illiteracy_by_country.drop(columns=['year']).describe().drop('count')
#Change themes
theme_stats_summary = summary_stats.style\
    .set_table_styles([
        {"selector": "th", "props": [("background-color", "#1E3A8A"), ("color", "white")]}
    ])\
    .set_properties(**{
        "background-color": "#F3F4F6",
        "color": "#111827",
        "border-color": "#CBD5E1"
    })
```

```{python}
#| echo: false
#| output: true
show(theme_stats_summary, allow_html=True, columnDefs=[
            {
                'targets': '_all',
                'className': 'dt-left'
            }
            ])
```

Frequency table of regions and income groups

```{python}
#| echo: false
#| output: true
income_freq_table = child_illiteracy_by_country['income_group'].value_counts().reset_index()
income_freq_table.columns = ['income_group', 'count']

theme_ift = income_freq_table.style\
    .set_table_styles([
        {"selector": "th", "props": [("background-color", "#8a641e"), ("color", "white")]}
    ])\
            .set_properties(**{
                "background-color": "#F3F4F6",
                "color": "#111827",
                "border-color": "#CBD5E1"
        })

show(theme_ift, allow_html=True, columnDefs=[
            {
                'targets': '_all',
                'className': 'dt-left'
            }
            ])

```

```{python}
#| echo: false
#| output: true
region_freq_table = child_illiteracy_by_country['region'].value_counts().reset_index()
region_freq_table.columns = ['region', 'count']

theme_rft = region_freq_table.style\
    .set_table_styles([
        {"selector": "th", "props": [("background-color", "#1e8a73"), ("color", "white")]}
    ])\
            .set_properties(**{
                "background-color": "#F3F4F6",
                "color": "#111827",
                "border-color": "#CBD5E1"
        })

show(theme_rft, allow_html=True, columnDefs=[
            {
                'targets': '_all',
                'className': 'dt-left'
            }
            ])
```



Mean of each numeric column by country, sorted from highest to lowest learning poverty percentage.
```{python}
#| echo: false
#| output: true

mean_country_learn = child_illiteracy_by_country.drop(columns=['year']).groupby('country').mean(numeric_only=True).reset_index()

high_mean_country_learn = mean_country_learn.sort_values(by="learning_poverty_pct", ascending = False)

theme_mean_country = high_mean_country_learn.style\
    .set_table_styles([
        {"selector": "th", "props": [("background-color", "#9c17d1"), ("color", "white")]}
    ])\
    .set_properties(**{
        "background-color": "#F3F4F6",
        "color": "#111827",
        "border-color": "#CBD5E1"
    })

show(theme_mean_country, allow_html=True, columnDefs=[
            {
                'targets': '_all',
                'className': 'dt-left'
            }
            ])
```

```{python}
#| echo: false
#| output: true
#| warning: false
#| fig-width: 8
#| fig-asp: 12

plt.figure(figsize=(8, 11))

sns.barplot(data = high_mean_country_learn, 
    x = "learning_poverty_pct", 
    y = "country", 
    errorbar=None, 
    palette="viridis", 
    hue="country")

plt.title("Average 10 Year Learning Poverty pct by Country", fontsize=16)

plt.tight_layout() 
plt.show()
```


Mean of each numeric column by income group.


```{python}
#| echo: false
#| output: true

median_income_group_learn = child_illiteracy_by_country.drop(columns=['year']).groupby('income_group').median(numeric_only=True).reset_index()

theme_median_income_group = median_income_group_learn.style\
    .set_table_styles([
        {"selector": "th", "props": [("background-color", "#9c17d1"), ("color", "white")]}
    ])\
    .set_properties(**{
        "background-color": "#F3F4F6",
        "color": "#111827",
        "border-color": "#CBD5E1"
    })

show(theme_median_income_group, allow_html=True, columnDefs=[
            {
                'targets': '_all',
                'className': 'dt-left'
            }
            ])
```

median of each numeric column by region

```{python}
#| echo: false
#| output: true

median_region_learn = child_illiteracy_by_country.drop(columns=['year']).groupby('region').median(numeric_only=True).reset_index()

theme_median_region = median_region_learn.style\
    .set_table_styles([
        {"selector": "th", "props": [("background-color", "#9c17d1"), ("color", "white")]}
    ])\
    .set_properties(**{
        "background-color": "#F3F4F6",
        "color": "#111827",
        "border-color": "#CBD5E1"
    })

show(theme_median_region, allow_html=True, columnDefs=[
            {
                'targets': '_all',
                'className': 'dt-left'
            }
            ])
```

### Exploratory Data Analysis of Variables
Below are the distributions of each of the numeric variables of each country averaged over 15 years. The distributions are shown as histograms with box plots as marginal plots. The box plots are notched to show the confidence interval around the median.

1. Taking a closer look at the distributions of each of the numeric variables in the child illiteracy by country data set. In the learning poverty pct we can see the distribution is slightly right skewed with a long tail, with the median falling at 45.52% and 1st and 3rd quartiles falling at 23.62% and 70.30% respectively.
2. In the primary completion rate we can see that the distribution is left skewed with a long tail, with the median falling at 75.87%, and 1st and 3rd quartiles falling at 61.16% and 86.99% respectively.
3. For the out of school rate we can see that the distribution is right skewed with a long right tail, with the median falling at 6.9% out of school. The interquartile range is 3.67% to 10.61% out of school rate.
4. For Foundational reading we can see that the distribution is left skewed with a long left tail, with the median falling at 52.75%, and 1st and 3rd quartiles falling at 27.81% and 74.59% respectively. Foundational numeracy has the same distribution as foundational reading, with the median falling at 50.41%, and 1st and 3rd quartiles falling at 24.91% and 71.2% respectively.
5. Gender Parity Index is left skewed with a long left tail and a outlier at 0.84 gender parity index. The median falls at 0.95 and the interquartile range is 0.93 to 0.97 gender. 
6. Government ecucation spending as a percentage of GDP is relatively normally distributed but has a number of outliers on the left of graph with very low government spending on education, the lowest being 3.27% of GDP. The median falls at 
7. On the pupil to teacher ratio we can see that the distribution is right skewed, and the median falls at 37.55 pupils per teacher, with the interquartile range falling at 22.675 to 46.63594
8. Lastly the estimated number of illiterate children in millions is very right skewed with the majority of the data falling in the 0 to 5 million range. There a large amount of outliers on the right of the distribution making the median fall at 2.75 million illiterate children, but having a max of 158.87; the next highest value being at 38.9 million illiterate children. The interquartile range falls at 950 thousand to 6.66 million estimated illiterate children.


```{python}
#| echo: false
#| output: true

features = [
    'learning_poverty_pct', 'primary_completion_rate_pct', 'out_of_school_rate_pct', 
    'foundational_reading_pct', 'foundational_numeracy_pct', 'gender_parity_index',
    'govt_education_spending_pct_gdp', 'pupil_teacher_ratio', 'est_illiterate_children_millions'
]

#Build Histograms for variable distributions with box plots as marginal plots. The first variable will be visible, the rest will be hidden and toggled via dropdown menu.

fig = px.histogram(
    mean_country_learn, 
    x=features[0], 
    marginal="box"
)

# Force the starting box plot trace to be notched
for trace in fig.data:
    if isinstance(trace, go.Box):
        trace.notched = True
    trace.marker.color = "teal"

for col in features[1:]:
    sub_fig = px.histogram(
        mean_country_learn, 
        x=col, 
        marginal="box"
    )
    
    for trace in sub_fig.data:
        if isinstance(trace, go.Box):
            trace.notched = True
        trace.marker.color = "teal"
        trace.visible = False
        fig.add_trace(trace)

# Create Toggle Buttons for Each Feature
buttons = []
traces_per_feature = 2
total_features = len(features)

for i, col in enumerate(features):
    clean_title = col.replace("_", " ").title()
    
    # Construct the boolean visibility array for this specific feature selection
    visibility_mask = []
    for f_idx in range(total_features):
        if f_idx == i:
            visibility_mask.extend([True] * traces_per_feature)
        else:
            visibility_mask.extend([False] * traces_per_feature)
            
    buttons.append(
        dict(
            label=clean_title,
            method="update",
            args=[
                {"visible": visibility_mask},  # Toggle the paired traces
                {
                    "title": f"Distribution of {clean_title}",
                    "xaxis.title.text": clean_title  # Dynamic axis label updates
                }
            ]
        )
    )

#Drop Down menu of toggle variables
fig.update_layout(
    updatemenus=[
        dict(
            buttons=buttons,
            direction="down",
            showactive=True,
            x=0.0,
            xanchor="left",
            y=1.22,  # Lifted higher so it doesn't overlap the top box subplot
            yanchor="top"
        )
    ],
    template="plotly_white",
    bargap=0.05
)

fig.show()

```